### ISSUE TITLE
Add redirection to login on 'Get started' button

### ISSUE THREAD

**Issue by Eragoo** [gerwld/coinchecker#48]
<img width="1145" alt="Screenshot 2022-05-10 at 11 26 11" src="https://user-images.githubusercontent.com/37846731/167584048-7e89c4c3-d784-4615-8428-154f5ffd78ef.png">
It will be great to redirect users to sign up by clicking on the 'Get started button.

**Comment by gerwld** [comment]
Add feature in #e25fd64e1deb95309da5621e803d593f82f33178

**Comment by ptjaworski** [comment]
Added this feature in #e25fd64e1deb95309da5621e803d593f82f33178
